//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DreamsEntities : DbContext
    {
        public DreamsEntities()
            : base("name=DreamsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Dream> Dreams { get; set; }
        public virtual DbSet<DreamAndCategory> DreamAndCategories { get; set; }
        public virtual DbSet<DreamAndTag> DreamAndTags { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Unconfirmed_Users> Unconfirmed_Users { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
