//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dream
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dream()
        {
            this.DreamAndCategories = new HashSet<DreamAndCategory>();
            this.DreamAndTags = new HashSet<DreamAndTag>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Long { get; set; }
        public string Lat { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string RealLat { get; set; }
        public string RealLong { get; set; }
        public bool isPublic { get; set; }
        public string Lang { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DreamAndCategory> DreamAndCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DreamAndTag> DreamAndTags { get; set; }
    }
}
