//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DreamAndTag
    {
        public int ID { get; set; }
        public int DreamID { get; set; }
        public int TagID { get; set; }
    
        public virtual Dream Dream { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
